abstract class AppStrings {
  static const String appName = 'appName',
      skip = 'skip',
      onBoradingTitle1 = 'onBoradingTitle1',
      onBoradingTitle2 = 'onBoradingTitle2',
      onBoradingTitle3 = 'onBoradingTitle3',
      onBoradingTitle4 = 'onBoradingTitle4',
      onBoradingSubTitle1 = 'onBoradingSubTitle1',
      onBoradingSubTitle2 = 'onBoradingSubTitle2',
      onBoradingSubTitle3 = 'onBoradingSubTitle3',
      onBoradingSubTitle4 = 'onBoradingSubTitle4',
      signInTitle = 'onBoradingSubTitle4',
      signInSubTitle = 'signInSubTitle',
      phone = "phone",
      email = "email",
      password = "password",
      userName = "userName",
      register = "register",
      signIn = "signIn",
      signUp = "signUp",
      back="back";
}
