abstract class AppStrings {
  static const String appName = 'appName',
      skip = 'skip',
      onBoradingTitle1 = 'onBoradingTitle1',
      onBoradingTitle2 = 'onBoradingTitle2',
      onBoradingTitle3 = 'onBoradingTitle3',
      onBoradingTitle4 = 'onBoradingTitle4',
      onBoradingSubTitle1 = 'onBoradingSubTitle1',
      onBoradingSubTitle2 = 'onBoradingSubTitle2',
      onBoradingSubTitle3 = 'onBoradingSubTitle3',
      onBoradingSubTitle4 = 'onBoradingSubTitle4',
      signInTitle = 'signInTitle',
      signInSubTitle = 'signInSubTitle',
      phone = "phone",
      email = "email",
      password = "password",
      userName = "userName",
      register = "register",
      signIn = "signIn",
      loginHint = "loginHint",
      confirmPassword = "confirmPassword",
      signUp = "signUp",
      back = "back",
      login = "login",
      send = "send",
      verify = "verify",
      reset = "reset",

      //!sign in
      pleaseEnterValidEmail = 'please_enter_email',
      pleaseEnterValidPassword = 'please_enter_valid_password',
      pleaseEnterValidPhone = 'please_enter_phone',
      forgetPassword = 'forgetPassword',
      forgetPasswordTitle = 'forgetPasswordTitle',
      dontHaveAcc = 'dontHaveAcc',
      //!register
      registerTitle = 'registerTitle',
      registerSubTitle = 'registerSubTitle',
      alredyHaveAcc = 'alredyHaveAcc',
      //!forget password
      forgetPasswordSubTitle = 'forgetPasswordSubTitle',
      checkInbox = 'checkInbox',
      //!passResetVerification
      passResetVerification = 'passResetVerification',
      passResetVerificationSubTitle = 'passResetVerificationSubTitle',
      resend = 'resend',
      resetPassword = 'resetPassword',
      resetPasswordSubTitle = 'resetPasswordSubTitle',
      dontCode = 'dontCode';
}
